---
- name: DNS fix
  hosts: all, !ipa1.idm.lab
  become: yes
  tasks:
    - name: NetworkManager dns configured
      copy:
        dest: /etc/NetworkManager/NetworkManager.conf
        content: |
          [main]
          dns=systemd-resolved
      notify: restart NetworkManager
    - name: systemd-resolved started
      service:
        service: systemd-resolved
        enabled: yes
        state: started
    - name: systemd-resolved configured
      copy:
        dest: /etc/systemd/resolved.conf 
        content: |
          [Resolve]
          DNS=192.168.55.11
          Domains=idm.lab ~idm.lab ~55.168.192.in-addr.arpa
          DNSSEC=no
      notify: restart systemd-resolved

  handlers:
    - name: restart NetworkManager
      service:
        service: NetworkManager
        state: restarted
    - name: restart systemd-resolved
      service:
        service: systemd-resolved
        state: restarted

- name: Install IPA servers
  hosts: ipa1.idm.lab
  become: true
  vars_files:
    - passwords.yml
  vars:
    - ipaserver_domain: idm.lab
    - ipaserver_realm: IDM.LAB
    - ipaserver_setup_dns: yes
    - ipaserver_auto_forwarders: yes
  roles:
    - role: ipaserver
      state: present

- name: Install IPA replicas
  hosts: ipa2.idm.lab
  become: true
  vars_files:
    - passwords.yml
  roles:
    - role: ipareplica
      state: present

- name: Install IPA clients
  hosts: logstash.idm.lab, ansible.idm.lab
  become: true
  vars_files:
    - passwords.yml
  roles:
  - role: ipaclient
    state: present
