---
- name: Install IPA servers
  hosts: ipa1.idm.lab
  become: true
  vars_files:
    - passwords.yml
  vars:
    - ipaserver_domain: idm.lab
    - ipaserver_realm: IDM.LAB
    - ipaserver_setup_dns: yes
    - ipaserver_auto_forwarders: yes
  pre_tasks:
    - name: DNS fixed
      replace:
        path: /etc/resolv.conf
        regexp: '^nameserver.*$'
        replace: 'nameserver 192.168.55.11'
  roles:
  - role: ipaserver
    state: present

- name: Install IPA replicas
  hosts: ipa2.idm.lab
  become: true
  vars_files:
    - passwords.yml
  pre_tasks:
    - name: DNS fixed
      replace:
        path: /etc/resolv.conf
        regexp: '^nameserver.*$'
        replace: 'nameserver 192.168.55.11'
  roles:
  - role: ipareplica
    state: present

- name: Install IPA clients
  hosts: logstash.idm.lab, ansible.idm.lab
  become: true
  vars_files:
    - passwords.yml
  pre_tasks:
    - name: DNS fixed
      replace:
        path: /etc/resolv.conf
        regexp: '^nameserver.*$'
        replace: 'nameserver 192.168.55.11'
  roles:
  - role: ipaclient
    state: present
